/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Sarah
 */
public class DataSelectionModesDialogue extends javax.swing.JDialog {

    /**
     * Creates new form DataSelectionModesDialogue
     */
    public DataSelectionModesDialogue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGroup1 = new javax.swing.ButtonGroup();
        pnCompanyName = new javax.swing.JPanel();
        lbCompanyName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnOptions = new javax.swing.JPanel();
        pnRadioButton = new javax.swing.JPanel();
        lbWhiteSpace1 = new javax.swing.JLabel();
        rbParticularTables = new javax.swing.JRadioButton();
        lbWhiteSpace2 = new javax.swing.JLabel();
        lbWhiteSpace3 = new javax.swing.JLabel();
        rbEntireDB = new javax.swing.JRadioButton();
        lbWhiteSpace4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btOK = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnCompanyName.setLayout(new java.awt.GridLayout(1, 2));

        lbCompanyName.setText("Company Name:");
        lbCompanyName.setMaximumSize(new java.awt.Dimension(40, 45));
        lbCompanyName.setMinimumSize(new java.awt.Dimension(40, 45));
        lbCompanyName.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCompanyName.add(lbCompanyName);

        jLabel1.setMaximumSize(new java.awt.Dimension(40, 45));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 45));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCompanyName.add(jLabel1);

        getContentPane().add(pnCompanyName, java.awt.BorderLayout.NORTH);

        pnOptions.setLayout(new java.awt.BorderLayout());

        pnRadioButton.setLayout(new java.awt.GridLayout(2, 3));
        pnRadioButton.add(lbWhiteSpace1);

        bgGroup1.add(rbParticularTables);
        rbParticularTables.setText("particular Tables");
        pnRadioButton.add(rbParticularTables);
        pnRadioButton.add(lbWhiteSpace2);
        pnRadioButton.add(lbWhiteSpace3);

        bgGroup1.add(rbEntireDB);
        rbEntireDB.setText("entire Database");
        pnRadioButton.add(rbEntireDB);
        pnRadioButton.add(lbWhiteSpace4);

        pnOptions.add(pnRadioButton, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        btOK.setText("OK");
        jPanel1.add(btOK);

        btCancel.setText("Cancel");
        jPanel1.add(btCancel);

        pnOptions.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnOptions, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSelectionModesDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSelectionModesDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSelectionModesDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSelectionModesDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataSelectionModesDialogue dialog = new DataSelectionModesDialogue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGroup1;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCompanyName;
    private javax.swing.JLabel lbWhiteSpace1;
    private javax.swing.JLabel lbWhiteSpace2;
    private javax.swing.JLabel lbWhiteSpace3;
    private javax.swing.JLabel lbWhiteSpace4;
    private javax.swing.JPanel pnCompanyName;
    private javax.swing.JPanel pnOptions;
    private javax.swing.JPanel pnRadioButton;
    private javax.swing.JRadioButton rbEntireDB;
    private javax.swing.JRadioButton rbParticularTables;
    // End of variables declaration//GEN-END:variables
}
