/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;

/**
 *
 * @author Steffie
 */
public class DetailsDialogue extends javax.swing.JDialog {

    /**
     * Creates new form DetailsDialogue
     */
    
    
    public DetailsDialogue(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        this.setSize(700,500);
        this.setResizable(false);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBottomBar = new javax.swing.JPanel();
        lbDate = new javax.swing.JLabel();
        btPreviousSide = new javax.swing.JButton();
        btNextSide = new javax.swing.JButton();
        pnContainer = new javax.swing.JPanel();
        pnCompany = new javax.swing.JPanel();
        spDetailsCompany = new javax.swing.JScrollPane();
        tbDetailsCompany = new javax.swing.JTable();
        pnCompanyText = new javax.swing.JPanel();
        lbCompanyName = new javax.swing.JLabel();
        lbCompanyTableName = new javax.swing.JLabel();
        pnCustomer = new javax.swing.JPanel();
        spDetailsCustomer = new javax.swing.JScrollPane();
        tbDetailsCustomer = new javax.swing.JTable();
        pnCustomerText = new javax.swing.JPanel();
        lbCustomerName = new javax.swing.JLabel();
        lbCustomerTableName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBottomBar.setLayout(new java.awt.BorderLayout());

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate.setText("08.07.2015");
        pnBottomBar.add(lbDate, java.awt.BorderLayout.CENTER);

        btPreviousSide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPreviousSide.setText("Previous");
        btPreviousSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPreviousSide(evt);
            }
        });
        pnBottomBar.add(btPreviousSide, java.awt.BorderLayout.WEST);

        btNextSide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNextSide.setText("Next");
        btNextSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNextSide(evt);
            }
        });
        pnBottomBar.add(btNextSide, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnBottomBar, java.awt.BorderLayout.SOUTH);

        pnContainer.setLayout(new java.awt.GridLayout(1, 2));

        pnCompany.setLayout(new java.awt.BorderLayout());

        tbDetailsCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spDetailsCompany.setViewportView(tbDetailsCompany);

        pnCompany.add(spDetailsCompany, java.awt.BorderLayout.CENTER);

        pnCompanyText.setLayout(new java.awt.GridLayout(2, 1));

        lbCompanyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCompanyName.setText("Principal");
        pnCompanyText.add(lbCompanyName);

        lbCompanyTableName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCompanyTableName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCompanyTableName.setText("Table Name");
        pnCompanyText.add(lbCompanyTableName);

        pnCompany.add(pnCompanyText, java.awt.BorderLayout.PAGE_START);

        pnContainer.add(pnCompany);

        pnCustomer.setLayout(new java.awt.BorderLayout());

        tbDetailsCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spDetailsCustomer.setViewportView(tbDetailsCustomer);

        pnCustomer.add(spDetailsCustomer, java.awt.BorderLayout.CENTER);

        pnCustomerText.setLayout(new java.awt.GridLayout(2, 1));

        lbCustomerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCustomerName.setText("Customer");
        pnCustomerText.add(lbCustomerName);

        lbCustomerTableName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCustomerTableName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomerTableName.setText("Table Name");
        pnCustomerText.add(lbCustomerTableName);

        pnCustomer.add(pnCustomerText, java.awt.BorderLayout.PAGE_START);

        pnContainer.add(pnCustomer);

        getContentPane().add(pnContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onPreviousSide(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPreviousSide
        // TODO add your handling code here:
    }//GEN-LAST:event_onPreviousSide

    private void onNextSide(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNextSide
        // TODO add your handling code here:
    }//GEN-LAST:event_onNextSide

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailsDialogue dialog = new DetailsDialogue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNextSide;
    private javax.swing.JButton btPreviousSide;
    private javax.swing.JLabel lbCompanyName;
    private javax.swing.JLabel lbCompanyTableName;
    private javax.swing.JLabel lbCustomerName;
    private javax.swing.JLabel lbCustomerTableName;
    private javax.swing.JLabel lbDate;
    private javax.swing.JPanel pnBottomBar;
    private javax.swing.JPanel pnCompany;
    private javax.swing.JPanel pnCompanyText;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnCustomer;
    private javax.swing.JPanel pnCustomerText;
    private javax.swing.JScrollPane spDetailsCompany;
    private javax.swing.JScrollPane spDetailsCustomer;
    private javax.swing.JTable tbDetailsCompany;
    private javax.swing.JTable tbDetailsCustomer;
    // End of variables declaration//GEN-END:variables
}
