/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Steffie
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form DiffToolGui
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnButtonToolBar = new javax.swing.JPanel();
        btCompareData = new javax.swing.JButton();
        btShowDetails = new javax.swing.JButton();
        btDownloadData = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        pnFirstDatabase = new javax.swing.JPanel();
        pnShowAllTables1 = new javax.swing.JPanel();
        btExtractData1 = new javax.swing.JButton();
        spTables1 = new javax.swing.JScrollPane();
        liTables1 = new javax.swing.JList();
        pnDetails = new javax.swing.JPanel();
        lbPrincipalName = new javax.swing.JLabel();
        pnNamesCounts = new javax.swing.JPanel();
        pnTableColumn = new javax.swing.JPanel();
        pnCounts = new javax.swing.JPanel();
        lbColumnCount = new javax.swing.JLabel();
        lbColumnCountValue = new javax.swing.JLabel();
        lbRowCount = new javax.swing.JLabel();
        lbRowCountValue = new javax.swing.JLabel();
        lbWhiteSpace3 = new javax.swing.JLabel();
        lbDistinctionCount = new javax.swing.JLabel();
        pnTableName = new javax.swing.JPanel();
        lbTableName = new javax.swing.JLabel();
        lbTableNameValue = new javax.swing.JLabel();
        pnColumnNames = new javax.swing.JPanel();
        lbColumnNames = new javax.swing.JLabel();
        spColumnNames = new javax.swing.JScrollPane();
        liColumnNamesValue = new javax.swing.JList();
        pnSecondDatabase = new javax.swing.JPanel();
        pnShowAllTables2 = new javax.swing.JPanel();
        btExtractData2 = new javax.swing.JButton();
        spTables2 = new javax.swing.JScrollPane();
        liTablesC = new javax.swing.JList();
        pnDetails1 = new javax.swing.JPanel();
        lbCustomerName = new javax.swing.JLabel();
        pnNamesCounts1 = new javax.swing.JPanel();
        pnTableColumn1 = new javax.swing.JPanel();
        pnCounts1 = new javax.swing.JPanel();
        lbColumnCountC = new javax.swing.JLabel();
        lbColumnCountValueC = new javax.swing.JLabel();
        lbRowCountC = new javax.swing.JLabel();
        lbRowCountValueC = new javax.swing.JLabel();
        lbDistinctionCountValue = new javax.swing.JLabel();
        lbWhiteSpaceC = new javax.swing.JLabel();
        pnTableName1 = new javax.swing.JPanel();
        lbTableNameC = new javax.swing.JLabel();
        lbTableNameValueC = new javax.swing.JLabel();
        pnColumnNames1 = new javax.swing.JPanel();
        lbColumnNamesC = new javax.swing.JLabel();
        spColumnNames1 = new javax.swing.JScrollPane();
        liColumnNamesValueC = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        pnButtonToolBar.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        btCompareData.setText("Compare Data");
        pnButtonToolBar.add(btCompareData);

        btShowDetails.setText("Show Details");
        btShowDetails.setToolTipText("");
        pnButtonToolBar.add(btShowDetails);

        btDownloadData.setText("Download data as text");
        btDownloadData.setToolTipText("");
        pnButtonToolBar.add(btDownloadData);

        getContentPane().add(pnButtonToolBar, java.awt.BorderLayout.PAGE_START);

        pnMain.setLayout(new java.awt.GridLayout(1, 2));

        pnFirstDatabase.setLayout(new java.awt.BorderLayout());

        pnShowAllTables1.setLayout(new java.awt.BorderLayout());

        btExtractData1.setText("Extract Data");
        btExtractData1.setToolTipText("");
        btExtractData1.setMaximumSize(new java.awt.Dimension(40, 45));
        btExtractData1.setMinimumSize(new java.awt.Dimension(40, 45));
        btExtractData1.setPreferredSize(new java.awt.Dimension(40, 45));
        pnShowAllTables1.add(btExtractData1, java.awt.BorderLayout.PAGE_START);

        spTables1.setMaximumSize(new java.awt.Dimension(100, 100));
        spTables1.setMinimumSize(new java.awt.Dimension(100, 100));
        spTables1.setPreferredSize(new java.awt.Dimension(100, 100));

        liTables1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        liTables1.setMaximumSize(new java.awt.Dimension(100, 100));
        liTables1.setMinimumSize(new java.awt.Dimension(100, 100));
        liTables1.setPreferredSize(new java.awt.Dimension(100, 100));
        spTables1.setViewportView(liTables1);

        pnShowAllTables1.add(spTables1, java.awt.BorderLayout.CENTER);

        pnFirstDatabase.add(pnShowAllTables1, java.awt.BorderLayout.WEST);

        pnDetails.setLayout(new java.awt.BorderLayout());

        lbPrincipalName.setText("Principal");
        lbPrincipalName.setMaximumSize(new java.awt.Dimension(40, 45));
        lbPrincipalName.setMinimumSize(new java.awt.Dimension(40, 45));
        lbPrincipalName.setPreferredSize(new java.awt.Dimension(40, 45));
        pnDetails.add(lbPrincipalName, java.awt.BorderLayout.PAGE_START);

        pnNamesCounts.setLayout(new java.awt.BorderLayout());

        pnTableColumn.setLayout(new java.awt.BorderLayout());

        pnCounts.setLayout(new java.awt.GridLayout(3, 2));

        lbColumnCount.setText("Column Count:");
        lbColumnCount.setMaximumSize(new java.awt.Dimension(40, 45));
        lbColumnCount.setMinimumSize(new java.awt.Dimension(40, 45));
        lbColumnCount.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts.add(lbColumnCount);

        lbColumnCountValue.setMaximumSize(new java.awt.Dimension(40, 45));
        lbColumnCountValue.setMinimumSize(new java.awt.Dimension(40, 45));
        lbColumnCountValue.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts.add(lbColumnCountValue);

        lbRowCount.setText("Row Count:");
        lbRowCount.setMaximumSize(new java.awt.Dimension(40, 45));
        lbRowCount.setMinimumSize(new java.awt.Dimension(40, 45));
        lbRowCount.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts.add(lbRowCount);

        lbRowCountValue.setMaximumSize(new java.awt.Dimension(40, 45));
        lbRowCountValue.setMinimumSize(new java.awt.Dimension(40, 45));
        lbRowCountValue.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts.add(lbRowCountValue);

        lbWhiteSpace3.setMaximumSize(new java.awt.Dimension(40, 45));
        lbWhiteSpace3.setMinimumSize(new java.awt.Dimension(40, 45));
        lbWhiteSpace3.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts.add(lbWhiteSpace3);

        lbDistinctionCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDistinctionCount.setText("Distinction Count:");
        lbDistinctionCount.setMaximumSize(new java.awt.Dimension(40, 45));
        lbDistinctionCount.setMinimumSize(new java.awt.Dimension(40, 45));
        lbDistinctionCount.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts.add(lbDistinctionCount);

        pnTableColumn.add(pnCounts, java.awt.BorderLayout.SOUTH);

        pnTableName.setLayout(new java.awt.GridLayout(1, 2));

        lbTableName.setText("Table name:");
        lbTableName.setMaximumSize(new java.awt.Dimension(40, 45));
        lbTableName.setMinimumSize(new java.awt.Dimension(40, 45));
        lbTableName.setPreferredSize(new java.awt.Dimension(40, 45));
        pnTableName.add(lbTableName);

        lbTableNameValue.setMaximumSize(new java.awt.Dimension(40, 45));
        lbTableNameValue.setMinimumSize(new java.awt.Dimension(40, 45));
        lbTableNameValue.setPreferredSize(new java.awt.Dimension(40, 45));
        pnTableName.add(lbTableNameValue);

        pnTableColumn.add(pnTableName, java.awt.BorderLayout.NORTH);

        pnColumnNames.setLayout(new java.awt.BorderLayout());

        lbColumnNames.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbColumnNames.setText("Column Names:");
        lbColumnNames.setMaximumSize(new java.awt.Dimension(40, 45));
        lbColumnNames.setMinimumSize(new java.awt.Dimension(40, 45));
        lbColumnNames.setPreferredSize(new java.awt.Dimension(40, 45));
        pnColumnNames.add(lbColumnNames, java.awt.BorderLayout.NORTH);

        liColumnNamesValue.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spColumnNames.setViewportView(liColumnNamesValue);

        pnColumnNames.add(spColumnNames, java.awt.BorderLayout.CENTER);

        pnTableColumn.add(pnColumnNames, java.awt.BorderLayout.CENTER);

        pnNamesCounts.add(pnTableColumn, java.awt.BorderLayout.CENTER);

        pnDetails.add(pnNamesCounts, java.awt.BorderLayout.CENTER);

        pnFirstDatabase.add(pnDetails, java.awt.BorderLayout.CENTER);

        pnMain.add(pnFirstDatabase);

        pnSecondDatabase.setLayout(new java.awt.BorderLayout());

        pnShowAllTables2.setLayout(new java.awt.BorderLayout());

        btExtractData2.setText("Extract Data");
        btExtractData2.setToolTipText("");
        btExtractData2.setMaximumSize(new java.awt.Dimension(40, 45));
        btExtractData2.setMinimumSize(new java.awt.Dimension(40, 45));
        btExtractData2.setPreferredSize(new java.awt.Dimension(40, 45));
        pnShowAllTables2.add(btExtractData2, java.awt.BorderLayout.PAGE_START);

        spTables2.setMaximumSize(new java.awt.Dimension(100, 100));
        spTables2.setMinimumSize(new java.awt.Dimension(100, 100));
        spTables2.setPreferredSize(new java.awt.Dimension(100, 100));

        liTablesC.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        liTablesC.setMaximumSize(new java.awt.Dimension(100, 100));
        liTablesC.setMinimumSize(new java.awt.Dimension(100, 100));
        liTablesC.setPreferredSize(new java.awt.Dimension(100, 100));
        spTables2.setViewportView(liTablesC);

        pnShowAllTables2.add(spTables2, java.awt.BorderLayout.CENTER);

        pnSecondDatabase.add(pnShowAllTables2, java.awt.BorderLayout.EAST);

        pnDetails1.setLayout(new java.awt.BorderLayout());

        lbCustomerName.setText("Customer");
        lbCustomerName.setMaximumSize(new java.awt.Dimension(40, 45));
        lbCustomerName.setMinimumSize(new java.awt.Dimension(40, 45));
        lbCustomerName.setPreferredSize(new java.awt.Dimension(40, 45));
        pnDetails1.add(lbCustomerName, java.awt.BorderLayout.PAGE_START);

        pnNamesCounts1.setLayout(new java.awt.BorderLayout());

        pnTableColumn1.setLayout(new java.awt.BorderLayout());

        pnCounts1.setLayout(new java.awt.GridLayout(3, 2));

        lbColumnCountC.setText("Column Count:");
        lbColumnCountC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbColumnCountC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbColumnCountC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts1.add(lbColumnCountC);

        lbColumnCountValueC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbColumnCountValueC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbColumnCountValueC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts1.add(lbColumnCountValueC);

        lbRowCountC.setText("Row Count:");
        lbRowCountC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbRowCountC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbRowCountC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts1.add(lbRowCountC);

        lbRowCountValueC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbRowCountValueC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbRowCountValueC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts1.add(lbRowCountValueC);

        lbDistinctionCountValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDistinctionCountValue.setMaximumSize(new java.awt.Dimension(40, 45));
        lbDistinctionCountValue.setMinimumSize(new java.awt.Dimension(40, 45));
        lbDistinctionCountValue.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts1.add(lbDistinctionCountValue);

        lbWhiteSpaceC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbWhiteSpaceC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbWhiteSpaceC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnCounts1.add(lbWhiteSpaceC);

        pnTableColumn1.add(pnCounts1, java.awt.BorderLayout.SOUTH);

        pnTableName1.setLayout(new java.awt.GridLayout(1, 2));

        lbTableNameC.setText("Table name:");
        lbTableNameC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbTableNameC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbTableNameC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnTableName1.add(lbTableNameC);

        lbTableNameValueC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbTableNameValueC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbTableNameValueC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnTableName1.add(lbTableNameValueC);

        pnTableColumn1.add(pnTableName1, java.awt.BorderLayout.NORTH);

        pnColumnNames1.setLayout(new java.awt.BorderLayout());

        lbColumnNamesC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbColumnNamesC.setText("Column Names:");
        lbColumnNamesC.setMaximumSize(new java.awt.Dimension(40, 45));
        lbColumnNamesC.setMinimumSize(new java.awt.Dimension(40, 45));
        lbColumnNamesC.setPreferredSize(new java.awt.Dimension(40, 45));
        pnColumnNames1.add(lbColumnNamesC, java.awt.BorderLayout.NORTH);

        liColumnNamesValueC.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spColumnNames1.setViewportView(liColumnNamesValueC);

        pnColumnNames1.add(spColumnNames1, java.awt.BorderLayout.CENTER);

        pnTableColumn1.add(pnColumnNames1, java.awt.BorderLayout.CENTER);

        pnNamesCounts1.add(pnTableColumn1, java.awt.BorderLayout.CENTER);

        pnDetails1.add(pnNamesCounts1, java.awt.BorderLayout.CENTER);

        pnSecondDatabase.add(pnDetails1, java.awt.BorderLayout.CENTER);

        pnMain.add(pnSecondDatabase);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompareData;
    private javax.swing.JButton btDownloadData;
    private javax.swing.JButton btExtractData1;
    private javax.swing.JButton btExtractData2;
    private javax.swing.JButton btShowDetails;
    private javax.swing.JLabel lbColumnCount;
    private javax.swing.JLabel lbColumnCountC;
    private javax.swing.JLabel lbColumnCountValue;
    private javax.swing.JLabel lbColumnCountValueC;
    private javax.swing.JLabel lbColumnNames;
    private javax.swing.JLabel lbColumnNamesC;
    private javax.swing.JLabel lbCustomerName;
    private javax.swing.JLabel lbDistinctionCount;
    private javax.swing.JLabel lbDistinctionCountValue;
    private javax.swing.JLabel lbPrincipalName;
    private javax.swing.JLabel lbRowCount;
    private javax.swing.JLabel lbRowCountC;
    private javax.swing.JLabel lbRowCountValue;
    private javax.swing.JLabel lbRowCountValueC;
    private javax.swing.JLabel lbTableName;
    private javax.swing.JLabel lbTableNameC;
    private javax.swing.JLabel lbTableNameValue;
    private javax.swing.JLabel lbTableNameValueC;
    private javax.swing.JLabel lbWhiteSpace3;
    private javax.swing.JLabel lbWhiteSpaceC;
    private javax.swing.JList liColumnNamesValue;
    private javax.swing.JList liColumnNamesValueC;
    private javax.swing.JList liTables1;
    private javax.swing.JList liTablesC;
    private javax.swing.JPanel pnButtonToolBar;
    private javax.swing.JPanel pnColumnNames;
    private javax.swing.JPanel pnColumnNames1;
    private javax.swing.JPanel pnCounts;
    private javax.swing.JPanel pnCounts1;
    private javax.swing.JPanel pnDetails;
    private javax.swing.JPanel pnDetails1;
    private javax.swing.JPanel pnFirstDatabase;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnNamesCounts;
    private javax.swing.JPanel pnNamesCounts1;
    private javax.swing.JPanel pnSecondDatabase;
    private javax.swing.JPanel pnShowAllTables1;
    private javax.swing.JPanel pnShowAllTables2;
    private javax.swing.JPanel pnTableColumn;
    private javax.swing.JPanel pnTableColumn1;
    private javax.swing.JPanel pnTableName;
    private javax.swing.JPanel pnTableName1;
    private javax.swing.JScrollPane spColumnNames;
    private javax.swing.JScrollPane spColumnNames1;
    private javax.swing.JScrollPane spTables1;
    private javax.swing.JScrollPane spTables2;
    // End of variables declaration//GEN-END:variables
}
