/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Sarah
 */
public class SelectDownloadModeDialogue extends javax.swing.JDialog {

    /**
     * Creates new form SelectDownloadModeDialogue
     */
    public SelectDownloadModeDialogue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGroup1 = new javax.swing.ButtonGroup();
        pnSelectionModes = new javax.swing.JPanel();
        pnRadios = new javax.swing.JPanel();
        rbPrincipal = new javax.swing.JRadioButton();
        rbCustomer = new javax.swing.JRadioButton();
        rbBoth = new javax.swing.JRadioButton();
        pnTables = new javax.swing.JPanel();
        spTables = new javax.swing.JScrollPane();
        jlTables = new javax.swing.JList();
        pnButtons = new javax.swing.JPanel();
        btDownlaod = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnSelectionModes.setLayout(new java.awt.GridLayout(1, 2));

        pnRadios.setLayout(new java.awt.GridLayout(3, 1));

        bgGroup1.add(rbPrincipal);
        rbPrincipal.setText("Principal");
        pnRadios.add(rbPrincipal);

        bgGroup1.add(rbCustomer);
        rbCustomer.setText("Customer");
        pnRadios.add(rbCustomer);

        bgGroup1.add(rbBoth);
        rbBoth.setText("Both");
        pnRadios.add(rbBoth);

        pnSelectionModes.add(pnRadios);

        pnTables.setLayout(new java.awt.BorderLayout());

        jlTables.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spTables.setViewportView(jlTables);

        pnTables.add(spTables, java.awt.BorderLayout.CENTER);

        pnSelectionModes.add(pnTables);

        getContentPane().add(pnSelectionModes, java.awt.BorderLayout.CENTER);

        pnButtons.setLayout(new java.awt.GridLayout(1, 2));

        btDownlaod.setText("Download");
        pnButtons.add(btDownlaod);

        btCancel.setText("Cancel");
        btCancel.setActionCommand("Cancel");
        pnButtons.add(btCancel);

        getContentPane().add(pnButtons, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectDownloadModeDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectDownloadModeDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectDownloadModeDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectDownloadModeDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectDownloadModeDialogue dialog = new SelectDownloadModeDialogue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGroup1;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDownlaod;
    private javax.swing.JList jlTables;
    private javax.swing.JPanel pnButtons;
    private javax.swing.JPanel pnRadios;
    private javax.swing.JPanel pnSelectionModes;
    private javax.swing.JPanel pnTables;
    private javax.swing.JRadioButton rbBoth;
    private javax.swing.JRadioButton rbCustomer;
    private javax.swing.JRadioButton rbPrincipal;
    private javax.swing.JScrollPane spTables;
    // End of variables declaration//GEN-END:variables
}
